# Generated by Django 3.0 on 2019-12-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_app.Author'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
