# Generated by Django 3.0.1 on 2020-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fancycat',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fancycat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
